// JavaScript Document
 $(function(){var html ='<!-- 职业技能开始 -->'
	html += '<ul class="menu">'
	html += '<li class="level1 leftgameTab1"><a href="javascript:void(0)" class="cur">门派介绍</a>'
	html += '<ul class="level2" style="display:block">'
	html += '<li>'
	html += '<a href="index-25.html">狂魔谷</a>'
	html += '<a href="index-28.html">飘渺崖</a>'
	html += '<a href="index-29.html">战皇殿</a>'	
	html += '<a href="index-27.html">青云峰</a>'
	html += '<a href="index-26.html">万邪墓</a>'	
	html += '<a href="index-24.html">修罗门</a>'
	html += '</li>'
	html += '</ul>'

	html += '</li>'
	html += '<li class="level1 leftgameTab2"><a href="javascript:void(0)">武器装备</a>'
	html += '<ul class="level2">'
	html += '<li>'
	html += '<a href="wuqi_1.shtml">武器</a>'
	html += '<a href="fangju_1.shtml">防具</a>'
	html += '<a href="shipin_1.shtml">饰品</a>'	
	html += '<a href="tz_mptz_1.shtml">套装</a>'
	html += '</li>'
	html += '</ul>'
	html += '</li>'
	html += '<li class="level1 leftgameTab3"><a href="javascript:void(0)">珍兽大全</a>'
	html += '<ul class="level2">'
	html += '<li>'
	html += '<a href="zsdq_1.shtml">珍兽大全</a>	'
	html += '<a href="http://sh3d.17173.com/tool/pet/simulate.shtml">珍兽查询器</a>'
	html += '<a href="zsjn_1.shtml">珍兽技能</a>	'
	html += '<a href="index-31.html">珍兽繁殖</a>'

	html += '</li>'
	html += '</ul>'
	html += '</li> ' 
	html += '<li class="level1 leftgameTab4"><a href="javascript:void(0)">活动副本</a>'
	html += '<ul class="level2">'
	html += '<li>'
	html += '<a href="index-39.html">大圣抢亲</a>'
	html += '<a href="index-176.html">五岳争霸</a>'
	html += '<a href="index-37.html">精卫填海</a>'	
	html += '<a href="index-44.html">至尊白虎</a>'

	html += '</li>'
	html += '</ul>'
	html += '</li>'
	html += '<li class="level1 leftgameTab5"><a href="javascript:void(0)">地图查询</a>'
	html += '<ul class="level2">'
	html += '<li>'
	html += '<a href="index-184.html">世界地图</a>'
	html += '<a href="index-142.html">野外地图</a>'
	html += '<a href="index-186.html">城市地图</a>'	
	html += '<a href="index-145.html">练功地图</a>'

	html += '</li>'
	html += '</ul>'
	html += '</li>'
	html += '<li class="level1 leftgameTab6"><a href="http://event.wushen.com/sh/strategy/index.php" id="hover7"  target="_blank" >攻略手册</a>'
	html += '</li>'
	html += '</ul>'
	$(".box").append(html);
})