// JavaScript Document
$(function(){
  var html = '<div id="home-content-nav">'
	  html += '<ul id="content_nav">'                
	  html += '<li class="downmenu downmenu1"><a href="javascript:void(0)">常用资料</a>'
	  html += '<ul style="top: 23px;">'
	  html += '<li><a href="index-51.html">门派介绍</a></li>'
	  html += '<li><a href="yu_1.shtml">道具物品</a></li>'
	  html += '<li><a href="wuqi_1.shtml">武器装备</a></li>'
	  html += '<li><a href="zsdq_1.shtml">珍兽系统</a></li>'
	  html += '<li><a href="index-52.html">坐骑系统</a></li>'
	  html += '<li><a href="npc_mp.shtml">NPC查询</a></li>'
	  html += '<li><a href="index-53.html">地图查询</a></li>'
	  html += '<li><a href="index-54.html">帮会系统</a></li>'
	  html += '<li><a href="index-55.html">摆摊系统</a></li>'
	  html += '<li><a href="index-56.html">帐号注册</a></li>'
	  html += '<li><a href="index-57.html">游戏下载</a></li>'
	  html += '<li><a href="index-58.html">系统配置</a></li>'
	  html += '<li><a href="index-59.html">登录游戏</a></li>'
		html += '<li><a href="index-60.html">创建角色</a></li>'
		html += '<li><a href="index-61.html">界面说明</a></li>'
		html += '<li><a href="index-62.html">江湖指南</a></li>'
	  html += '</ul>'
	  html += '</li>'
	  
		html += '<li class="downmenu downmenu2"><a href="javascript:void(0)">初入江湖</a>'
		html += '<ul style="top: 23px;">'
		html += '<li><a href="index-63.html">新手引导</a></li>'
		html += '<li><a href="index-64.html">新手教程</a></li>'
		html += '<li><a href="index-65.html">常用功能</a></li>'
		html += '<li><a href="index-66.html">玩法介绍</a></li>'
		html += '<li><a class="sub" target="_blank" href="index-67.html">技能大全</a>'
		html += '<ul style="top: -1px;">'
		html += '<li><a href="index-67.html">普通技能</a></li>'
		html += '<li><a class="sub" href="index-68.html">战斗技能</a>'
		html += '<ul style="top: -1px;">'
		html += '<li><a href="index-69.html">修罗</a></li>'
		html += '<li><a href="index-68.html">狂魔</a></li>'
		html += '<li><a href="index-70.html">战皇</a></li>'
		html += '<li><a href="index-71.html">万邪</a></li>'
		html += '<li><a href="index-72.html">青云</a></li>'
		html += '<li><a href="index-73.html">飘渺</a></li>'
		html += '</ul>'
		html += '</li>'
		html += '<li><a class="sub" href="index-74.html">生活技能</a>'
		html += '<ul style="top: -1px;">'
		html += '<li><a href="index-75.html">基本</a></li>'
		html += '<li><a href="index-74.html">门派</a></li>'
		html += '</ul>'
		html += '</li>'
		html += '</ul>'
		html += '</li>'
		html += '</ul>'
		html += '</li>'
	  
		html += '<li class="downmenu"><a href="javascript:void(0)">升级通道</a>'
		html += '<ul style="top: 23px;">'
		html += '<li><a href="index-76.html">怪物分布</a></li>'
		html += '<li><a class="sub" href="xsrw_1.shtml">任务攻略</a>'
		html += '<ul style="top: -1px;">'
		html += '<li><a href="xsrw_1.shtml">新手任务</a></li>'
		html += '<li><a href="slrw_1.shtml">试炼任务</a></li>'
		html += '<li><a href="cjrw_1.shtml">成就任务</a></li>'
		html += '<li><a href="index-77.html">师门任务</a></li>'
		html += '<li><a href="chjingrw_1.shtml">场景任务</a></li>'
		html += '<li><a href="index-78.html">帮会任务</a></li>'
		html += '</ul>'
		html += '</li>'
   		html += '<li><a class="sub" href="index-79.html">活动系统</a>'
		html += '<ul style="top: -1px;">'
		html += '<li><a class="first dir sub" href="index-79.html">每日活动</a>'
		html += '<ul style="top: -1px;">'
		html += '<li><a href="">云南探宝</a></li>'
		html += '<li><a href="index-79.html">大圣抢亲</a></li>'
		html += '<li><a href="index-80.html">仕林救母</a></li>'
		html += '<li><a href="index-81.html">三打白骨精</a></li>'
		html += '<li><a href="index-82.html">花妖蝶王</a></li>'
		html += '<li><a href="index-83.html">星云天宫</a></li>'
		html += '<li><a href="index-84.html">邪魔入侵</a></li>'
		html += '<li><a href="index-85.html">天书奇谭</a></li>'
		html += '<li><a href="index-86.html">大圣盗宝</a></li>'
		html += '<li><a href="index-87.html">天降鸿福</a></li>'
		html += '<li><a href="index-88.html">BOSS群活动</a></li>'
		html += '<li><a href="index-89.html">365个思念</a></li>'
		html += '<li><a href="index-90.html">笔武大会</a></li>'
		html += '<li><a href="index-91.html">妖圣下凡</a></li>'
		html += '<li><a href="index-92.html">古墓夺宝</a></li>'
		html += '<li><a href="index-93.html">BOSS巡逻队</a></li>'
		html += '<li><a href="index-94.html">哪吒闹海</a></li>'
		html += '<li><a href="index-95.html">叱咤四海</a></li>'
		html += '<li><a href="index-96.html">生死蝶缘</a></li>'
		html += '<li><a href="index-97.html">龙脉传奇</a></li>'
		html += '<li><a href="index-98.html">灵兽峰抢宝箱</a></li>'
		html += '<li><a href="index-99.html">至尊白虎</a></li>'		
		html += '</ul>'
		html += '</li>'
		html += '<li><a class="sub" href="index-100.html">周/月活动</a>'
		html += '<ul style="top: -1px;">'
		html += '<li><a href="index-100.html">精卫填海</a></li>'
		html += '<li><a href="index-101.html">云游四海</a></li>'
		html += '<li><a href="index-102.html">五岳争霸</a></li>'
		html += '</ul>'
		html += '</li>'
		html += '<li><a class="first dir sub" href="index-103.html">升级奖励活动</a>'
		html += '<ul style="top: -1px;">'
		html += '<li><a href="index-103.html">四海结金兰</a></li>'
		html += '<li><a href="index-104.html">幸运聚宝盆</a></li>'
		html += '</ul>'
		html += '</li>'
		
		
		html += '<li><a class="sub" href="index-76.html">节日活动</a>'
		html += '<ul style="top: -1px;">'
		html += '<li><a href="4151292896353.html">圣诞元旦双节</a></li>'
		html += '</ul>'
		html += '</li>'
		html += '</ul>'
		html += '</li>'	
		html += '</ul>'
		html += '</li>'
	  
		html += '<li class="downmenu downmenu4"><a href="javascript:void(0)">高手进阶</a>'
		html += '<ul style="top: 23px;">'
		html += '<li><a href="index-105.html">装备强化</a></li>'
		html += '<li><a href="index-106.html">神器缎造</a></li>'
		html += '<li><a href="index-107.html">PK系统</a></li>'
		html += '<li><a href="index-108.html">宝石使用</a></li>'
		html += '<li><a href="index-55.html">玩家商店</a></li>'
		html += '<li><a href="index-109.html">元宝寄售</a></li>'
		html += '</ul>'
		html += '</li>'
		
		html += '<li class="downmenu downmenu5"><a href="javascript:void(0)">帐号安全</a>'
		html += '<ul style="top: 23px;">'
		html += '<li><a target="_blank" href="index-110.html">游戏安全</a></li>'
		html += '<li><a href="index-111.html">密保卡</a></li>'
		html += '</ul>'
		html += '</li>'
		
		html += '<li class="downmenu downmenu6"><a href="javascript:void(0)">最新更新</a>'
		html += '<ul style="top: 23px;">'
		html += '<li><a target="_blank" href="index-112.html">终极内测</a></li>'
		html += '</ul>'
		html += '</li>'
		html += '</ul>'
		html += '</div>'
	  $("#subnav").append(html);	
})